name: Space_the New frontier
favicon: null
layout_spectrum: 0.31280435365624726
typography_spectrum: 0.6274644841905683
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6028560940176249
  lightness: 0.9477138016372919
  saturation: 0.6387476688250899
  rhythmicContrast: 0.8307116425130516
purpose: []
